export const items = [
  {
    id: 1,
    name: "Mona Lisa by Leonardo da Vinci (1503-1505)",
    blurb: "A portrait of Madame Gherardini, personifying the ideal woman of the Renaissance. ",
    rating: 5,
    image: '/art1.png',
  },
  {
    id: 2,
    name: "The Birth of Venus by Sandro Botticelli (1486)",
    blurb: "Botticelli's painting illustrates the myth of the birth of Aphrodite. The beautiful goddess drifts to the shore in a sea shell, driven by the Zephyr's wind (West wind), and on the shore she is met by one of the Graces. ",
    rating: 5,
    image: '/art2.png',
  },
  {
    id: 3,
    name: "The Creation of Adam by Michelangelo Buonarroti (1511)",
    blurb: "Michelangelo's fresco The Creation of Adam, which adorns the ceiling of the Sistine Chapel in the Vatican Palace, is the fourth of the nine famous art pieces of the central composition dedicated to scenes from the Book of Genesis.",
    rating: 4,
    image: '/art3.png',
  },
    {
    id: 4,
    name: "Girl with a Pearl Earring by Johannes Vermeer (1665)",
    blurb: "Girl with a Pearl Earring by Dutch artist Jan Vermeer is often referred to as the northern Mona Lisa. This is not only because of its extraordinary popularity, but also because the expression on the girl's face is difficult to capture and explain.",
    rating: 5,
    image: '/art4.png',
  },
  {
    id: 5,
    name: "The Night Watch by Rembrandt van Rijn (1642)",
    blurb: "In the 19th century, art critics who discovered the painting thought that human figures were standing against a dark background, and it was called The Night Watch.",
    rating: 5,
    image: '/art5.png',
  },
  {
    id: 6,
    name: " Las Meninas by Diego Velázquez (1656)",
    blurb: "Las Meninas, depicts five-year-old Infanta Margarita in front of a portrait of her parents. The picture includes several plans: the characters pose for the painter, are reflected in the mirror, and leave the room. ",
    rating: 4,
    image: '/art6.png',
  },
    {
    id: 7,
    name: "The Persistence of Memory by Salvador Dalí (1931)",
    blurb: "The picture was painted as a result of abstract associations that Dali had at the sight of processed cheese.",
    rating: 5,
    image: '/art7.png',
  },
  {
    id: 8,
    name: "The Kiss by Gustav Klimt (1907–1908)",
    blurb: "The kiss is one of the first works of art in L'Art Nouveau or modern style. This painting, almost entirely done in gold tones, is one of the most striking artworks of the style.",
    rating: 5,
    image: '/art8.png',
  },
  {
    id: 9,
    name: "The Great Wave of Kanagawa by Katsushika Hokusai (1831)",
    blurb: "Hokusai's The Great Wave of Kanagawa, also known as The Great Wave or The Wave, is one of the most famous paintings of Japanese master. It is part of a series of 36 ukiyo prints of Mount Fuji.",
    rating: 4,
    image: '/art9.png',
  },
];